name: Build Python Executables

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
env:
  # https://flet.dev/docs/publish#versioning
  PYTHON_VERSION: 3.12.6

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: pyinstaller --onefile --noconsole --icon=./GUI-ver/icon.ico ./GUI-ver/flet-ui.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: windows-build
          path: ./dist/flet-ui.exe
